#if !canImport(ObjectiveC)
import XCTest

extension ULIDTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ULIDTests = [
        ("testFromString", testFromString),
        ("testMaxULID", testMaxULID),
        ("testRandomEncoding", testRandomEncoding),
        ("testTimeEncoding", testTimeEncoding),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ULIDTests.__allTests__ULIDTests),
    ]
}
#endif
